name: Flutter Nightly Build

on:
  workflow_dispatch: # 允许手动点击按钮触发
  push:
    branches:
      - master
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
